model: Category
table:
  title: Categories
  scope: alpha
  columns:
    title:
      heading: Title
  buttons:
    new: New Category
form:
  buttons:
    delete: Delete Category
  new: &new
    title: New Category
    fields:
      title:
        type: string
  edit:
    <<: *new
    title: Edit Category
