model: Idea
table:
  title: Ideas
  scope: with_includes.by_most_recent
  columns:
    title:
      heading: Title
    category:
      heading: Category
    status:
      heading: Status
    creator:
      heading: Creator
  buttons:
    new: New Idea
export:
  button: Export Ideas
  columns:
    title:
      label: Title
    desc_md:
      label: Description
    category:
      label: Category
    status:
      label: Status
    creator:
      label: Creator
form:
  new: &new
    title: New Idea
    fields:
      title:
        type: string
      desc_md:
        label: Description
        type: markdown
      category_id:
        type: select
        options: Category.all
      status_id:
        type: select
        options: Status.all
      creator_id:
        type: select
        options: User.all
  edit:
    <<: *new
    title: Edit Idea
