dashboard:
  label: Dashboard
  route: cambium.admin_dashboard
  icon: dashboard
ideas:
  label: Ideas
  route: main_app.admin_ideas
  icon: wand
  controllers: ['ideas']
categories:
  label: Categories
  route: main_app.admin_categories
  icon: folder
  controllers: ['categories']
statuses:
  label: Statuses
  route: main_app.admin_statuses
  icon: notification
  controllers: ['statuses']
users:
  label: Users
  route: cambium.admin_users
  icon: users
  controllers: ['users']
back_to_site:
  label: Back to Site
  route: main_app.root
  icon: arrow-left
  controllers: []