model: Status
table:
  title: Statuses
  scope: alpha
  columns:
    title:
      heading: Title
  buttons:
    new: New Status
form:
  buttons:
    delete: Delete Status
  new: &new
    title: New Status
    fields:
      title:
        type: string
  edit:
    <<: *new
    title: Edit Status
