model: User
table:
  title: Site Users
  scope: all
  columns:
    email:
      heading: Email
  buttons:
    new: New User
export:
  button: Export Users
  columns:
    name:
      label: Name
    email:
      label: Email
form:
  new: &new
    title: New User
    fields:
      name:
        type: string
      email:
        type: string
      password:
        type: password
      password_confirmation:
        type: password
  edit:
    <<: *new
    title: Edit User
