model: User
table:
  title: Site Users
  scope: all
  columns:
    name:
      heading: Name
    email:
      heading: Email
  buttons:
    new: New User
form:
  new: &new
    title: New User
    fields:
      name:
        type: string
      email:
        type: string
      is_admin:
        label: Admin?
        type: boolean
      password:
        type: password
      password_confirmation:
        type: password
  edit:
    <<: *new
    title: Edit User
